// Every page on the site: [file, title, keywords, one-line description]. Used by Octee Search and JoelAI.
export const PAGES = [
  ["index.html", "Home", "welcome main start front", "The front page. You were already here, in a way."],
  ["destinations.html", "Destinations", "destination places where travel city country fly to", "Places we fly to, and places we mean to."],
  ["book.html", "Book a Flight", "book buy ticket reserve flight fare price", "Book a flight, and be sorry later."],
  ["status.html", "Flight Status", "status flight delayed time arrival departure board", "The status of every flight. It is the same status."],
  ["checkin.html", "Check-in", "check in checkin seat boarding pass online", "Check in for a flight you have not taken."],
  ["baggage.html", "Baggage", "baggage bag luggage suitcase allowance weight", "Rules for bags, one of which is a wonky link."],
  ["bagtrack.html", "Bag Tracker", "bag tracker tag luggage lost wander", "Watch a bag wander around the airport."],
  ["experience.html", "In-Flight", "in flight inflight cabin seat service onboard", "What happens in the air. Mostly waiting."],
  ["fia.html", "FIA Airport", "airport fia terminal gate map", "The airport. It has a runway somewhere."],
  ["joelmobile.html", "JOELMOBILE", "joelmobile car ride taxi transport joel drive", "Joel will drive you there. Joel has questions."],
  ["cupboard.html", "Joel's Cupboard", "cupboard joel sandwich closet", "Where Joel lives when he runs out of sorry."],
  ["oneunited.html", "One United", "united partner alliance merger", "A partnership nobody has explained."],
  ["reviews.html", "Reviews", "reviews rating stars feedback customer", "Five stars. Mostly from us."],
  ["octmiles.html", "Octmiles", "miles points loyalty frequent flyer octmiles tokens", "Points that you earn and cannot use."],
  ["cargo.html", "Octee Airline Cargo", "cargo shipping parcel package lost bag peanut mystery object Fujitech", "Ship any parcel between Octee airports; fare depends on weight and route."],
  ["about.html", "About", "about us company history team who", "About us. We are sorry about us."],
  ["zhang-gullet.html", "Zhang Gullet", "zhang gullet head customer service profile about mr gullet staff", "Meet Mr Gullet. He is at his desk."],
  ["gullet-complaints.html", "Zhang Gullet Complaints Office", "complaint complain zhang gullet letter angry upset ticket office", "Complain to Mr Gullet in person. He replies by hand."],
  ["gullet-hold.html", "Zhang Gullet Hold Line", "hold line call phone queue waiting music zhang gullet telephone tuesday", "Call Mr Gullet. You are caller number 1."],
  ["customer-service.html", "Zhang Gullet Customer Service", "customer service zhang gullet gulletai help support refund manager escalate ticket hold", "Ask GulletAI. Your call is important to us."],
  ["gullet-complaints.html", "Zhang Gullet Complaints", "zhang gullet complaint complaints office letter ticket angry upset", "Complain to Mr Gullet. He will write back."],
  ["contact.html", "Contact", "contact phone email help support reach", "Contact us. We will contact you back. Eventually."],
  ["complaint.html", "Complaint Desk", "complain complaint desk refund compensation anger", "Complain, and get peanuts."],
  ["peanuts.html", "Peanut Wallet", "peanut wallet shop currency money", "Your peanuts and the shop that takes them."],
  ["lostfound.html", "Lost and Found", "lost found missing item claim lost property", "Report or claim lost things."],
  ["upgrade.html", "Upgrade Lottery", "upgrade lottery spin wheel seat class", "Spin for an upgrade that is not better."],
  ["news.html", "The Octee Times", "news newspaper crossword horoscope story times", "News, horoscope, crossword."],
  ["terminal-maps.html", "TDA and MFIA Maps", "terminal map tda mfia tabletop mt fuji gates gate hub transit", "Gates and maps for our two newest airports."],
  ["normal-thursday.html", "Normal Thursday Log", "normal thursday incident log safety oa 014 peanut fault report", "Every incident is a normal Thursday."],
  ["flight-radar.html", "Flight-Radar 25", "flight radar flightradar live planes map tracker 24 25 sky", "Every plane in the air. Better than 24."],
  ["runway.html", "FIA Runway Status", "runway weather wind rain conditions status", "Runway conditions and sorrow."],
  ["meal.html", "Meal Pre-order", "meal food dish dinner hungry order peanut", "Pre-order a peanut meal."],
  ["bingo.html", "Delay Bingo", "bingo delay card game certificate", "Bingo, on your own delay."],
  ["baggame.html", "The Baggage Game", "game baggage conveyor belt push play", "A game with a T-shaped belt."],
  ["safety.html", "Safety Demo", "safety demo quiz seatbelt life jacket oxygen brace", "Six cards and a quiz. No buckle."],
  ["safetycard.html", "Safety Card", "safety card print printable seat pocket", "A printable card for your seat pocket."],
  ["radio.html", "Octee Radio", "radio music songs station listen fm announcement", "Delay FM and other stations."],
  ["dutyfree.html", "Duty Free", "duty free shop buy souvenir perfume", "Things you cannot take on board."],
  ["auction.html", "Lost Property Auction", "auction bid bags lost property winning", "Bid on bags you cannot open."],
  ["creditcard.html", "Octee Credit Card", "credit card payment apply purchase bank", "Always approved, always declined."],
  ["cockpit.html", "The Cockpit", "cockpit pilot dials buttons captain controls", "Dials, buttons and one marked Do not."],
  ["wifi.html", "Octee Wi-Fi", "wifi wi-fi internet network speed test connect", "Connects. Loads. Negative speed."],
  ["magazine.html", "In-Flight Magazine", "magazine articles sudoku puzzle adverts read", "Articles and a sudoku with no solution."],
  ["insurance.html", "Octee Insurance", "insurance insure policy claim cover protection", "Covers everything except what happens."],
  ["departures.html", "Departures Board", "departures board flip delayed flights all delayed full screen", "A flip board where every flight is delayed."],
  ["entertainment.html", "Entertainment", "entertainment games play game bored delayed fun plane clicker memory waiting", "Airport games for when you are delayed."],
  ["account.html", "Backup code", "backup code restore account incognito another device miles", "Restore your account in any browser."],
  ["entertainment.html", "Hangman: Destination Edition", "hangman guess airport fia letters game", "Guess the airport. The answer is always FIA."],
  ["whackajoel.html", "Whack-a-Joel", "whack joel hammer cupboard game sorry mole", "Hit Joel with a hammer when he pops up."],
  ["apology.html", "Our Apology", "apology sorry apologise letter", "A long, sincere apology."],
  ["login.html", "Log in / Sign up", "login log in sign up account register password", "Log in. Or sign up and be welcomed."]
];
