CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  username_key TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
  token_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  expires_at TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS profiles (
  user_id INTEGER PRIMARY KEY,
  body TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS attempts (
  k TEXT PRIMARY KEY,
  n INTEGER NOT NULL DEFAULT 0,
  until INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_sessions_exp ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS reviews (
  user_id INTEGER PRIMARY KEY,
  username TEXT NOT NULL,
  stars INTEGER NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  date TEXT NOT NULL,
  route TEXT NOT NULL DEFAULT '',
  trip_ref TEXT NOT NULL DEFAULT '',
  verified INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_reviews_upd ON reviews(updated_at);
CREATE TABLE IF NOT EXISTS joel_wallet (
  user_id INTEGER PRIMARY KEY,
  pro INTEGER NOT NULL DEFAULT 0,
  paid INTEGER NOT NULL DEFAULT 0,
  month TEXT NOT NULL,
  used INTEGER NOT NULL DEFAULT 0,
  in_t INTEGER NOT NULL DEFAULT 0,
  out_t INTEGER NOT NULL DEFAULT 0,
  total_t INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS joel_ledger (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  at TEXT NOT NULL,
  kind TEXT NOT NULL,
  octee INTEGER NOT NULL DEFAULT 0,
  joel INTEGER NOT NULL DEFAULT 0,
  model TEXT NOT NULL DEFAULT '',
  in_t INTEGER NOT NULL DEFAULT 0,
  out_t INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_joel_ledger_user ON joel_ledger(user_id, id);
CREATE TABLE IF NOT EXISTS cloud_admins (
  user_id INTEGER PRIMARY KEY,
  granted_by INTEGER NOT NULL,
  granted_at TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (granted_by) REFERENCES users(id)
);
